-- EnergyDB PostgreSQL schema.
-- Owns: hierarchy (node, edge) + series metadata + run metadata.
-- All time-series data (the values themselves) live in ClickHouse via timedb.

CREATE SCHEMA IF NOT EXISTS energydb;

CREATE TABLE IF NOT EXISTS energydb.node (
    node_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_type   TEXT NOT NULL,
    name        TEXT NOT NULL,
    parent_id   BIGINT REFERENCES energydb.node(node_id) ON DELETE CASCADE,
    data        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT node_child_uniq UNIQUE (name, node_type, parent_id)
);
CREATE INDEX IF NOT EXISTS ix_node_parent_id ON energydb.node(parent_id);
CREATE INDEX IF NOT EXISTS ix_node_data_gin  ON energydb.node USING GIN(data);


CREATE TABLE IF NOT EXISTS energydb.edge (
    edge_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edge_type     TEXT NOT NULL,
    name          TEXT,
    from_node_id  BIGINT NOT NULL REFERENCES energydb.node(node_id) ON DELETE CASCADE,
    to_node_id    BIGINT NOT NULL REFERENCES energydb.node(node_id) ON DELETE CASCADE,
    data          JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT edge_uniq UNIQUE (edge_type, from_node_id, to_node_id)
);


-- Series metadata.
--   timeseries_type  (FLAT | OVERLAPPING)  — semantic flag. Mutable: a series
--                    can legitimately shift from flat to overlapping when the
--                    producer starts supplying knowledge_time.
--   retention        (short | medium | long) — tier. Immutable after insert
--                    (guarded by trigger). Reclassification = register new
--                    series or read-and-reinsert.
--   canonical_unit   Immutable after insert.
--   owner (node_id/edge_id) — Immutable after insert.
CREATE TABLE IF NOT EXISTS energydb.series (
    series_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id         BIGINT REFERENCES energydb.node(node_id) ON DELETE CASCADE,
    edge_id         BIGINT REFERENCES energydb.edge(edge_id) ON DELETE CASCADE,
    data_type       TEXT NOT NULL,
    name            TEXT NOT NULL,
    canonical_unit  TEXT NOT NULL,
    timeseries_type TEXT NOT NULL,
    retention       TEXT NOT NULL,
    description     TEXT,
    inserted_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT series_owner_xor       CHECK ((node_id IS NULL) <> (edge_id IS NULL)),
    CONSTRAINT series_node_uniq       UNIQUE (node_id, data_type, name),
    CONSTRAINT series_edge_uniq       UNIQUE (edge_id, data_type, name),
    CONSTRAINT valid_timeseries_type  CHECK (timeseries_type IN ('FLAT','OVERLAPPING')),
    CONSTRAINT valid_retention        CHECK (retention IN ('short','medium','long'))
);
CREATE INDEX IF NOT EXISTS ix_series_node ON energydb.series(node_id) WHERE node_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_series_edge ON energydb.series(edge_id) WHERE edge_id IS NOT NULL;


CREATE OR REPLACE FUNCTION energydb._series_guard_immutable()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.retention      IS DISTINCT FROM OLD.retention
    OR NEW.canonical_unit IS DISTINCT FROM OLD.canonical_unit
    OR NEW.node_id        IS DISTINCT FROM OLD.node_id
    OR NEW.edge_id        IS DISTINCT FROM OLD.edge_id THEN
        RAISE EXCEPTION
            'energydb.series: retention, canonical_unit, and owner columns '
            'are immutable. Register a new series to change tier, unit, or '
            'ownership.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS series_guard_immutable ON energydb.series;
CREATE TRIGGER series_guard_immutable
    BEFORE UPDATE ON energydb.series
    FOR EACH ROW EXECUTE FUNCTION energydb._series_guard_immutable();


-- Run metadata. Client-generated BIGINT run_id (uuid7 truncated to 64 bits,
-- or Snowflake). timedb also stores run_id on every event row, plus a tiny
-- run_series mapping table in ClickHouse for reverse lookups.
CREATE TABLE IF NOT EXISTS energydb.runs (
    run_id          BIGINT PRIMARY KEY,
    workflow_id     TEXT,
    model_name      TEXT,
    run_start_time  TIMESTAMPTZ,
    run_finish_time TIMESTAMPTZ,
    run_params      JSONB NOT NULL DEFAULT '{}'::jsonb,
    inserted_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_runs_workflow ON energydb.runs(workflow_id, inserted_at DESC);
