-- EnergyDB PostgreSQL schema.
-- Owns: hierarchy (node, edge) + series metadata.
-- Series row names a target ClickHouse table (validated app-side against
-- timedb.TABLES). Physical properties (target_table, canonical_unit, owner)
-- are immutable after registration — reclassification = new series_id.

CREATE SCHEMA IF NOT EXISTS energydb;

CREATE TABLE IF NOT EXISTS energydb.node (
    node_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_type   TEXT NOT NULL,
    name        TEXT NOT NULL,
    parent_id   BIGINT REFERENCES energydb.node(node_id) ON DELETE CASCADE,
    data        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT node_child_uniq UNIQUE (name, node_type, parent_id)
);
CREATE INDEX IF NOT EXISTS ix_node_parent_id ON energydb.node(parent_id);
CREATE INDEX IF NOT EXISTS ix_node_data_gin  ON energydb.node USING GIN(data);


CREATE TABLE IF NOT EXISTS energydb.edge (
    edge_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edge_type     TEXT NOT NULL,
    name          TEXT,
    from_node_id  BIGINT NOT NULL REFERENCES energydb.node(node_id) ON DELETE CASCADE,
    to_node_id    BIGINT NOT NULL REFERENCES energydb.node(node_id) ON DELETE CASCADE,
    data          JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT edge_uniq UNIQUE (edge_type, from_node_id, to_node_id)
);


CREATE TABLE IF NOT EXISTS energydb.series (
    series_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id         BIGINT REFERENCES energydb.node(node_id) ON DELETE CASCADE,
    edge_id         BIGINT REFERENCES energydb.edge(edge_id) ON DELETE CASCADE,
    data_type       TEXT NOT NULL,
    name            TEXT NOT NULL,
    canonical_unit  TEXT NOT NULL,
    target_table    TEXT NOT NULL,
    description     TEXT,
    inserted_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT series_owner_xor CHECK ((node_id IS NULL) <> (edge_id IS NULL)),
    CONSTRAINT series_node_uniq UNIQUE (node_id, data_type, name),
    CONSTRAINT series_edge_uniq UNIQUE (edge_id, data_type, name)
);
CREATE INDEX IF NOT EXISTS ix_series_node ON energydb.series(node_id) WHERE node_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_series_edge ON energydb.series(edge_id) WHERE edge_id IS NOT NULL;


CREATE OR REPLACE FUNCTION energydb._series_guard_immutable()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.target_table   IS DISTINCT FROM OLD.target_table
    OR NEW.canonical_unit IS DISTINCT FROM OLD.canonical_unit
    OR NEW.node_id        IS DISTINCT FROM OLD.node_id
    OR NEW.edge_id        IS DISTINCT FROM OLD.edge_id THEN
        RAISE EXCEPTION
            'energydb.series: target_table, canonical_unit, and owner columns '
            'are immutable. Register a new series to change storage routing, '
            'unit, or ownership.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS series_guard_immutable ON energydb.series;
CREATE TRIGGER series_guard_immutable
    BEFORE UPDATE ON energydb.series
    FOR EACH ROW EXECUTE FUNCTION energydb._series_guard_immutable();
